# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15.3

    working_directory: ~/repo

    steps:
      - checkout


      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}


      - run: yarn test
      
  deploy-job:
    docker:
         - image: my-image-version-tag
    working_directory: /tmp/my-project
    steps:
      - run: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN

    workflows:
      version: 2

      -deploy:
        jobs:
          - build-job
          - deploy-job:
              requires:
                - build-job
              filters:
                branches:
                  only: master